# Generated by Django 4.0.6 on 2022-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contributors', models.CharField(max_length=400)),
                ('iswc', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'musicals_musical',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='musicals_user',
        ),
    ]
