# Generated by Django 4.0.6 on 2022-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicals', '0002_musical_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'musicals_contributor',
            },
        ),
        migrations.RemoveField(
            model_name='musical',
            name='contributors',
        ),
        migrations.AddField(
            model_name='musical',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to='musicals.contributor'),
        ),
    ]
