# Generated by Django 4.0.6 on 2022-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicals', '0003_contributor_remove_musical_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical',
            name='contributors',
            field=models.ManyToManyField(related_name='musicals', to='musicals.contributor'),
        ),
    ]
